// ─── Map System ─────────────────────────────────────────────────────────────
// Procedurally generates a 160x160 tile city map with 10 distinct
// neighborhoods, roads, buildings, parks, water, and cover objects.
// Produces NYC-style dense rectangular city blocks: solid WALL interiors
// with streets forming a connected grid. Claimable storefront buildings
// are carved into block edges, facing the road.
// Provides the Phaser tilemap (isometric), terrain queries, and pathfinding grids.

import Phaser from 'phaser';
import {
  TILE_WIDTH,
  TILE_HEIGHT,
  MAP_WIDTH,
  MAP_HEIGHT,
  TerrainType,
  TERRAIN_COSTS,
  VEHICLE_TERRAIN_COSTS,
} from '../data/config';
import { BuildingType, BUILDING_DEFS } from '../data/buildings';

// ─── Public interfaces ──────────────────────────────────────────────────────

export interface BuildingPlacement {
  type: BuildingType;
  tileX: number;
  tileY: number;
  owner: number; // -1 = neutral, 0 = P1, 1 = P2
}

export interface StreetCornerPlacement {
  id: number;
  tileX: number;
  tileY: number;
  neighborhood: string;
}

export interface CityBlock {
  tileX: number;
  tileY: number;
  widthTiles: number;
  heightTiles: number;
}

// ─── Neighborhood definitions ────────────────────────────────────────────────

interface NeighborhoodDef {
  name: string;
  x: number;
  y: number;
  w: number;
  h: number;
  color: number; // tint applied to road/sidewalk tiles
}

const NEIGHBORHOODS: NeighborhoodDef[] = [
  { name: 'P1 Start', x: 0, y: 120, w: 40, h: 40, color: 0x442222 },
  { name: 'P2 Start', x: 120, y: 0, w: 40, h: 40, color: 0x222244 },
  { name: 'The Waterfront', x: 0, y: 0, w: 60, h: 20, color: 0x224444 },
  { name: 'Downtown', x: 60, y: 60, w: 40, h: 40, color: 0x444422 },
  { name: 'The Bottoms', x: 0, y: 60, w: 40, h: 40, color: 0x333322 },
  { name: 'Entertainment Row', x: 100, y: 80, w: 40, h: 40, color: 0x442244 },
  { name: 'The Heights', x: 60, y: 20, w: 50, h: 40, color: 0x334433 },
  { name: 'Industrial', x: 0, y: 20, w: 40, h: 40, color: 0x3a3a2a },
  { name: 'Market District', x: 100, y: 40, w: 40, h: 40, color: 0x443333 },
  { name: 'Rail District', x: 120, y: 120, w: 40, h: 40, color: 0x3a3a3a },
];

// ─── Seeded PRNG (simple LCG for deterministic maps) ────────────────────────

class SeededRandom {
  private state: number;

  constructor(seed: number = 42) {
    this.state = seed;
  }

  /** Returns a float in [0, 1). */
  next(): number {
    this.state = (this.state * 1664525 + 1013904223) & 0xffffffff;
    return (this.state >>> 0) / 0x100000000;
  }

  /** Returns an integer in [min, max). */
  int(min: number, max: number): number {
    return min + Math.floor(this.next() * (max - min));
  }

  /** Shuffle an array in place. */
  shuffle<T>(arr: T[]): T[] {
    for (let i = arr.length - 1; i > 0; i--) {
      const j = this.int(0, i + 1);
      [arr[i], arr[j]] = [arr[j], arr[i]];
    }
    return arr;
  }
}

// ─── MapSystem ──────────────────────────────────────────────────────────────

export class MapSystem {
  private scene: Phaser.Scene;
  private grid: TerrainType[][] = []; // [y][x]
  private rng: SeededRandom;

  constructor(scene: Phaser.Scene, seed: number = 42) {
    this.scene = scene;
    this.rng = new SeededRandom(seed);
    this.initGrid();
  }

  // ── Grid initialisation ─────────────────────────────────────────────────

  /** Fill the entire grid with WALL as a base — blocks are solid by default. */
  private initGrid(): void {
    this.grid = [];
    for (let y = 0; y < MAP_HEIGHT; y++) {
      this.grid[y] = new Array<TerrainType>(MAP_WIDTH).fill(
        TerrainType.WALL,
      );
    }
  }

  // ── Public API ──────────────────────────────────────────────────────────

  /** Generate the complete city. Call once before renderMap. */
  generateCity(): void {
    this.layRoadGrid();
    this.fillCityBlocks();
    this.addAlleys();
    this.addParks();
    this.addWaterAndBridges();
    this.addCoverObjects();
  }

  /**
   * Create and return a Phaser Tilemap with ISOMETRIC orientation from the
   * generated grid data. Uses Phaser's native isometric tilemap support
   * which handles diamond-shaped tile rendering, camera culling, and
   * coordinate conversion automatically.
   *
   * The tileset uses 64x32 diamond tiles generated by BootScene.
   *
   * Note: Phaser's `make.tilemap({ data })` always creates an ORTHOGONAL
   * map internally (Parse2DArray doesn't support orientation). We patch the
   * orientation on the Tilemap and its LayerData BEFORE creating the visual
   * layer so that TilemapLayer picks up isometric rendering, culling, and
   * coordinate conversion functions.
   */
  renderMap(): Phaser.Tilemaps.Tilemap {
    // Build raw tilemap data (2D array of tile indices matching TerrainType)
    const mapData: number[][] = [];
    for (let y = 0; y < MAP_HEIGHT; y++) {
      mapData[y] = [];
      for (let x = 0; x < MAP_WIDTH; x++) {
        mapData[y][x] = this.grid[y][x]; // TerrainType enum === tile index
      }
    }

    // Create tilemap from 2D array (defaults to orthogonal internally)
    const tilemap = this.scene.make.tilemap({
      data: mapData,
      tileWidth: TILE_WIDTH,
      tileHeight: TILE_HEIGHT,
    });

    // Patch orientation to ISOMETRIC on the Tilemap and its internal
    // LayerData so that createLayer() builds an isometric TilemapLayer
    // with the correct render/cull/coordinate functions.
    const ISO = Phaser.Tilemaps.Orientation.ISOMETRIC;
    (tilemap as any).orientation = ISO;
    for (const layerData of tilemap.layers) {
      (layerData as any).orientation = ISO;
    }

    const tileset = tilemap.addTilesetImage(
      'terrain',
      'terrain-tileset',
      TILE_WIDTH,
      TILE_HEIGHT,
      0,
      0,
    );

    if (!tileset) {
      console.error('MapSystem: failed to create tileset');
      return tilemap;
    }

    // Position the layer so Phaser's isometric tile rendering aligns with
    // our tileToWorld() coordinate system (which adds MAP_HEIGHT * TILE_WIDTH/2
    // as an x-offset to center the diamond in world space).
    const layer = tilemap.createLayer(0, tileset, MAP_HEIGHT * TILE_WIDTH / 2, 0);

    if (layer) {
      // Apply neighborhood tints to road and sidewalk tiles
      this.applyNeighborhoodTints(layer);

      // Mark collision tiles (walls, water, cover objects)
      layer.setCollisionByExclusion([
        TerrainType.ROAD,
        TerrainType.SIDEWALK,
        TerrainType.BUILDING_FLOOR,
        TerrainType.ALLEY,
        TerrainType.PARK,
        TerrainType.BRIDGE,
      ]);

      // Set the layer depth to 0 so it renders behind game objects
      layer.setDepth(0);
    }

    return tilemap;
  }

  /** Get the terrain type at a tile coordinate. */
  getTerrain(x: number, y: number): TerrainType {
    if (x < 0 || x >= MAP_WIDTH || y < 0 || y >= MAP_HEIGHT) {
      return TerrainType.WATER; // out of bounds = impassable
    }
    return this.grid[y][x];
  }

  /** Check if a tile is passable for the given movement mode. */
  isWalkable(x: number, y: number, isVehicle: boolean): boolean {
    const terrain = this.getTerrain(x, y);
    const costs = isVehicle ? VEHICLE_TERRAIN_COSTS : TERRAIN_COSTS;
    return isFinite(costs[terrain]);
  }

  /** 2D grid for infantry pathfinding: 0 = walkable, 1 = blocked. */
  getWalkableGrid(): number[][] {
    const result: number[][] = [];
    for (let y = 0; y < MAP_HEIGHT; y++) {
      result[y] = [];
      for (let x = 0; x < MAP_WIDTH; x++) {
        result[y][x] = isFinite(TERRAIN_COSTS[this.grid[y][x]]) ? 0 : 1;
      }
    }
    return result;
  }

  /** 2D grid for vehicle pathfinding: 0 = walkable, 1 = blocked. */
  getVehicleGrid(): number[][] {
    const result: number[][] = [];
    for (let y = 0; y < MAP_HEIGHT; y++) {
      result[y] = [];
      for (let x = 0; x < MAP_WIDTH; x++) {
        result[y][x] = isFinite(VEHICLE_TERRAIN_COSTS[this.grid[y][x]])
          ? 0
          : 1;
      }
    }
    return result;
  }

  /**
   * Place capturable buildings as storefronts on the edges of city blocks.
   * Buildings are carved out of solid WALL blocks, creating BUILDING_FLOOR
   * interiors accessible from the adjacent street.
   */
  placeBuildings(): BuildingPlacement[] {
    const placements: BuildingPlacement[] = [];

    // Building pool per neighborhood (type + owner)
    // Player start neighborhoods get a Compound; others get neutral buildings
    const neutralPool: BuildingType[] = [
      BuildingType.SPEAKEASY,
      BuildingType.CORNER_STORE,
      BuildingType.BACK_ALLEY_STILL,
      BuildingType.BOOKIE_JOINT,
      BuildingType.WAREHOUSE,
      BuildingType.BOXING_GYM,
      BuildingType.NIGHTCLUB,
      BuildingType.DISTILLERY,
      BuildingType.TRUCKING_DEPOT,
      BuildingType.PAWN_SHOP,
      BuildingType.CASINO,
      BuildingType.NEWSPAPER_OFFICE,
    ];

    for (const hood of NEIGHBORHOODS) {
      const owner = hood.name === 'P1 Start' ? 0 : hood.name === 'P2 Start' ? 1 : -1;

      // Find block-edge storefront candidates inside this neighborhood
      const edgeSpots = this.findBlockEdgeSpots(
        hood.x,
        hood.y,
        hood.w,
        hood.h,
      );

      // Shuffle candidates for variety
      this.rng.shuffle(edgeSpots);

      let placed = 0;
      // Dense urban feel: many buildings per neighborhood.
      // Player starts get 8 (compound + 7 others), neutral neighborhoods get 10-15.
      const maxBuildings = hood.name.startsWith('P') && owner >= 0 ? 8 : this.rng.int(10, 16);

      // Player start gets a Compound first — placed at a block corner
      // for maximum street exposure
      if (owner >= 0) {
        const compoundDef = BUILDING_DEFS[BuildingType.COMPOUND];
        // Place compound near center of the start neighborhood
        const cx = hood.x + Math.floor(hood.w / 2) - Math.floor(compoundDef.widthTiles / 2);
        const cy = hood.y + Math.floor(hood.h / 2) - Math.floor(compoundDef.heightTiles / 2);
        // Search with a wider radius to find a block-corner spot
        const spot = this.findBlockEdgeClearSpot(
          cx, cy, compoundDef.widthTiles, compoundDef.heightTiles, 10,
        );
        if (spot) {
          placements.push({
            type: BuildingType.COMPOUND,
            tileX: spot.x,
            tileY: spot.y,
            owner,
          });
          this.stampBuildingFootprint(spot.x, spot.y, compoundDef.widthTiles, compoundDef.heightTiles);
          placed++;
        }
      }

      // Special: Waterfront gets import docks
      if (hood.name === 'The Waterfront') {
        const dockDef = BUILDING_DEFS[BuildingType.IMPORT_DOCK];
        for (let d = 0; d < 2 && edgeSpots.length > 0; d++) {
          const pt = edgeSpots.pop()!;
          const spot = this.findBlockEdgeClearSpot(
            pt.x, pt.y, dockDef.widthTiles, dockDef.heightTiles, 6,
          );
          if (spot) {
            placements.push({
              type: BuildingType.IMPORT_DOCK,
              tileX: spot.x,
              tileY: spot.y,
              owner: -1,
            });
            this.stampBuildingFootprint(spot.x, spot.y, dockDef.widthTiles, dockDef.heightTiles);
            placed++;
          }
        }
      }

      // Downtown gets a City Hall Contact
      if (hood.name === 'Downtown' && edgeSpots.length > 0) {
        const chDef = BUILDING_DEFS[BuildingType.CITY_HALL_CONTACT];
        const pt = edgeSpots.pop()!;
        const spot = this.findBlockEdgeClearSpot(
          pt.x, pt.y, chDef.widthTiles, chDef.heightTiles, 6,
        );
        if (spot) {
          placements.push({
            type: BuildingType.CITY_HALL_CONTACT,
            tileX: spot.x,
            tileY: spot.y,
            owner: -1,
          });
          this.stampBuildingFootprint(spot.x, spot.y, chDef.widthTiles, chDef.heightTiles);
          placed++;
        }
      }

      // Fill remaining slots with random neutral buildings along block edges.
      // Cycle through the pool repeatedly so we can place many buildings
      // without being capped by the pool size.
      const shuffledPool = [...neutralPool];
      this.rng.shuffle(shuffledPool);
      let poolIdx = 0;

      while (placed < maxBuildings && edgeSpots.length > 0) {
        const bType = shuffledPool[poolIdx % shuffledPool.length];
        poolIdx++;
        const def = BUILDING_DEFS[bType];
        const pt = edgeSpots.pop()!;
        const spot = this.findBlockEdgeClearSpot(
          pt.x, pt.y, def.widthTiles, def.heightTiles, 8,
        );
        if (spot) {
          placements.push({
            type: bType,
            tileX: spot.x,
            tileY: spot.y,
            owner: owner >= 0 ? owner : -1,
          });
          this.stampBuildingFootprint(spot.x, spot.y, def.widthTiles, def.heightTiles);
          placed++;
        }
      }
    }

    console.log(`MapSystem: placed ${placements.length} buildings (target: 100-130)`);
    return placements;
  }

  /**
   * Place 3 StreetCorner markers per neighborhood at major intersections.
   * Returns ~30 corner placements total.
   */
  placeStreetCorners(): StreetCornerPlacement[] {
    const corners: StreetCornerPlacement[] = [];
    let id = 0;

    for (const hood of NEIGHBORHOODS) {
      // Find major road intersections (where two 2-tile-wide roads cross)
      const majors = this.findMajorIntersections(hood.x, hood.y, hood.w, hood.h);
      this.rng.shuffle(majors);

      const count = Math.min(3, majors.length);
      for (let i = 0; i < count; i++) {
        corners.push({
          id: id++,
          tileX: majors[i].x,
          tileY: majors[i].y,
          neighborhood: hood.name,
        });
      }
    }

    return corners;
  }

  /** Return the neighborhood name for a given tile position. */
  getNeighborhoodAt(x: number, y: number): string {
    // Check in definition order; first match wins (neighborhoods may overlap
    // at edges, so order in the array determines priority).
    for (const hood of NEIGHBORHOODS) {
      if (
        x >= hood.x &&
        x < hood.x + hood.w &&
        y >= hood.y &&
        y < hood.y + hood.h
      ) {
        return hood.name;
      }
    }
    return 'Unknown';
  }

  /**
   * Scan the terrain grid and return rectangular WALL clusters that form
   * city blocks. Uses the road grid's predictable 8-tile interval structure.
   * Each detected block represents the solid WALL interior of a sub-block,
   * suitable for drawing a visual skyscraper on top.
   */
  detectCityBlocks(): CityBlock[] {
    const blocks: CityBlock[] = [];

    for (let by = 0; by < MAP_HEIGHT; by += 8) {
      for (let bx = 0; bx < MAP_WIDTH; bx += 8) {
        const interior = this.getBlockInterior(bx, by);
        if (!interior) continue;

        const { x0, y0, x1, y1 } = interior;
        const w = x1 - x0 + 1;
        const h = y1 - y0 + 1;

        // Only count it as a city block if the interior is large enough
        // and mostly WALL (>50% of tiles)
        if (w < 2 || h < 2) continue;

        let wallCount = 0;
        const totalTiles = w * h;
        for (let yy = y0; yy <= y1; yy++) {
          for (let xx = x0; xx <= x1; xx++) {
            if (this.grid[yy][xx] === TerrainType.WALL) {
              wallCount++;
            }
          }
        }

        if (wallCount / totalTiles > 0.5) {
          blocks.push({
            tileX: x0,
            tileY: y0,
            widthTiles: w,
            heightTiles: h,
          });
        }
      }
    }

    return blocks;
  }

  // ─── City Generation Internals ──────────────────────────────────────────

  /**
   * Lay down major and minor roads on a grid pattern.
   * - Major roads every 16 tiles: 2-tile-wide road + 1 sidewalk each side
   * - Minor roads every 8 tiles: 1-tile-wide road + sidewalk one side
   */
  private layRoadGrid(): void {
    for (let y = 0; y < MAP_HEIGHT; y++) {
      for (let x = 0; x < MAP_WIDTH; x++) {
        const onMajorX = x % 16 === 0 || x % 16 === 1;
        const onMajorY = y % 16 === 0 || y % 16 === 1;
        const sidewalkMajorX = x % 16 === 15 || x % 16 === 2;
        const sidewalkMajorY = y % 16 === 15 || y % 16 === 2;
        const onMinorX = x % 8 === 0;
        const onMinorY = y % 8 === 0;
        const sidewalkMinorX = x % 8 === 1 || x % 8 === 7;
        const sidewalkMinorY = y % 8 === 1 || y % 8 === 7;

        if (onMajorX || onMajorY) {
          this.grid[y][x] = TerrainType.ROAD;
        } else if (sidewalkMajorX || sidewalkMajorY) {
          this.grid[y][x] = TerrainType.SIDEWALK;
        } else if (onMinorX || onMinorY) {
          this.grid[y][x] = TerrainType.ROAD;
        } else if (sidewalkMinorX || sidewalkMinorY) {
          // Only place sidewalk next to a minor road if there IS a minor
          // road adjacent (avoid sidewalk in the middle of a block)
          if (
            (sidewalkMinorX && (this.isRoadAt(x - 1, y) || this.isRoadAt(x + 1, y))) ||
            (sidewalkMinorY && (this.isRoadAt(x, y - 1) || this.isRoadAt(x, y + 1)))
          ) {
            this.grid[y][x] = TerrainType.SIDEWALK;
          }
        }
      }
    }
  }

  /** Quick check for road placement (used during road-grid pass). */
  private isRoadAt(x: number, y: number): boolean {
    if (x < 0 || x >= MAP_WIDTH || y < 0 || y >= MAP_HEIGHT) return false;
    return this.grid[y][x] === TerrainType.ROAD;
  }

  /**
   * Fill city blocks with SOLID WALL. Every tile between roads/sidewalks
   * that isn't already a road or sidewalk becomes impassable wall.
   * This creates dense NYC-style blocks that units must path around
   * via the street grid. Buildings are later carved into block edges.
   */
  private fillCityBlocks(): void {
    // The grid was initialized to WALL, and layRoadGrid() placed ROAD
    // and SIDEWALK tiles. Everything else is already WALL — so we just
    // need to verify that no stray BUILDING_FLOOR tiles remain.
    // (This is already satisfied since initGrid fills with WALL.)
    // Nothing more to do here — blocks are solid by default.
  }

  /**
   * Returns the bounding box {x0,y0,x1,y1} of WALL tiles within a sub-block
   * starting at (bx, by). Scans all tiles in the 8x8 region and finds the
   * tightest rectangle enclosing all WALL tiles.
   */
  private getBlockInterior(
    bx: number,
    by: number,
  ): { x0: number; y0: number; x1: number; y1: number } | null {
    const endX = Math.min(bx + 7, MAP_WIDTH - 1);
    const endY = Math.min(by + 7, MAP_HEIGHT - 1);

    let x0 = endX + 1;
    let y0 = endY + 1;
    let x1 = bx - 1;
    let y1 = by - 1;

    for (let yy = by; yy <= endY; yy++) {
      for (let xx = bx; xx <= endX; xx++) {
        if (this.grid[yy][xx] === TerrainType.WALL) {
          if (xx < x0) x0 = xx;
          if (xx > x1) x1 = xx;
          if (yy < y0) y0 = yy;
          if (yy > y1) y1 = yy;
        }
      }
    }

    if (x0 > x1 || y0 > y1) return null;
    return { x0, y0, x1, y1 };
  }

  private isTileRoadOrSidewalk(x: number, y: number): boolean {
    if (x < 0 || x >= MAP_WIDTH || y < 0 || y >= MAP_HEIGHT) return true;
    const t = this.grid[y][x];
    return t === TerrainType.ROAD || t === TerrainType.SIDEWALK;
  }

  /**
   * Cut alleys through some building blocks. An alley is a 1-tile-wide
   * passable path that splits a block, allowing infantry shortcuts.
   * Works with the new solid blocks by carving through WALL tiles.
   */
  private addAlleys(): void {
    // For roughly 25% of sub-blocks, cut a horizontal or vertical alley
    for (let by = 0; by < MAP_HEIGHT; by += 8) {
      for (let bx = 0; bx < MAP_WIDTH; bx += 8) {
        if (this.rng.next() > 0.25) continue;

        const interior = this.getBlockInterior(bx, by);
        if (!interior) continue;
        const { x0, y0, x1, y1 } = interior;
        if (x1 - x0 < 4 || y1 - y0 < 4) continue;

        const horizontal = this.rng.next() < 0.5;
        if (horizontal) {
          const ay = Math.floor((y0 + y1) / 2);
          for (let xx = x0; xx <= x1; xx++) {
            this.grid[ay][xx] = TerrainType.ALLEY;
          }
        } else {
          const ax = Math.floor((x0 + x1) / 2);
          for (let yy = y0; yy <= y1; yy++) {
            this.grid[yy][ax] = TerrainType.ALLEY;
          }
        }
      }
    }
  }

  /**
   * Place 2-3 small parks (8x8 tiles each) at random spots.
   * These overwrite whatever is there (wall, floor).
   */
  private addParks(): void {
    const parkCount = this.rng.int(2, 4);
    const placed: { x: number; y: number }[] = [];

    let attempts = 0;
    while (placed.length < parkCount && attempts < 50) {
      attempts++;
      // Pick a random block-aligned position away from map edges
      const px = this.rng.int(2, (MAP_WIDTH / 8) - 2) * 8;
      const py = this.rng.int(3, (MAP_HEIGHT / 8) - 2) * 8; // y>=3 to avoid water zone

      // Don't overlap player starts
      const inP1 = px < 40 && py >= 120;
      const inP2 = px >= 120 && py < 40;
      if (inP1 || inP2) continue;

      // Don't overlap existing parks
      const tooClose = placed.some(
        (p) => Math.abs(p.x - px) < 16 && Math.abs(p.y - py) < 16,
      );
      if (tooClose) continue;

      // Stamp the park
      for (let yy = py; yy < py + 8 && yy < MAP_HEIGHT; yy++) {
        for (let xx = px; xx < px + 8 && xx < MAP_WIDTH; xx++) {
          this.grid[yy][xx] = TerrainType.PARK;
        }
      }
      placed.push({ x: px, y: py });
    }
  }

  /**
   * Fill top 8 rows with water, then punch 3 bridge crossings through.
   */
  private addWaterAndBridges(): void {
    const waterDepth = 8;

    // Fill water
    for (let y = 0; y < waterDepth; y++) {
      for (let x = 0; x < MAP_WIDTH; x++) {
        this.grid[y][x] = TerrainType.WATER;
      }
    }

    // Place 3 bridges at major north-south roads
    // Major roads are at x positions: 0,1, 16,17, 32,33, 48,49, ...
    const bridgeXPositions: number[] = [];
    for (let rx = 0; rx < MAP_WIDTH; rx += 16) {
      bridgeXPositions.push(rx);
    }
    this.rng.shuffle(bridgeXPositions);

    const bridgeCount = 3;
    for (let i = 0; i < bridgeCount && i < bridgeXPositions.length; i++) {
      const bx = bridgeXPositions[i];
      // Bridge is 4 tiles wide (road + sidewalks)
      for (let y = 0; y < waterDepth; y++) {
        for (let dx = -1; dx <= 2; dx++) {
          const xx = bx + dx;
          if (xx >= 0 && xx < MAP_WIDTH) {
            this.grid[y][xx] = TerrainType.BRIDGE;
          }
        }
      }
    }
  }

  /**
   * Scatter COVER_OBJECT tiles along sidewalks and at intersections
   * to represent parked cars, crates, sandbags, etc.
   */
  private addCoverObjects(): void {
    for (let y = 0; y < MAP_HEIGHT; y++) {
      for (let x = 0; x < MAP_WIDTH; x++) {
        if (this.grid[y][x] !== TerrainType.SIDEWALK) continue;
        // Only place cover on ~4% of sidewalk tiles
        if (this.rng.next() > 0.04) continue;
        // Must be adjacent to a road
        const adjRoad =
          this.getTerrain(x - 1, y) === TerrainType.ROAD ||
          this.getTerrain(x + 1, y) === TerrainType.ROAD ||
          this.getTerrain(x, y - 1) === TerrainType.ROAD ||
          this.getTerrain(x, y + 1) === TerrainType.ROAD;
        if (adjRoad) {
          this.grid[y][x] = TerrainType.COVER_OBJECT;
        }
      }
    }
  }

  // ─── Neighborhood tint helpers ──────────────────────────────────────────

  /**
   * Apply a subtle colour tint to road and sidewalk tiles so each
   * neighborhood is visually distinct. Phaser tilemap tiles support
   * per-tile tint via the `tint` property. This works the same way
   * for both orthogonal and isometric tilemaps.
   */
  private applyNeighborhoodTints(
    layer: Phaser.Tilemaps.TilemapLayer,
  ): void {
    for (const hood of NEIGHBORHOODS) {
      for (let y = hood.y; y < hood.y + hood.h && y < MAP_HEIGHT; y++) {
        for (let x = hood.x; x < hood.x + hood.w && x < MAP_WIDTH; x++) {
          const terrain = this.grid[y][x];
          if (
            terrain === TerrainType.ROAD ||
            terrain === TerrainType.SIDEWALK
          ) {
            const tile = layer.getTileAt(x, y);
            if (tile) {
              tile.tint = hood.color;
            }
          }
        }
      }
    }
  }

  // ─── Block-edge storefront placement helpers ──────────────────────────

  /**
   * Find WALL tiles on block edges that are adjacent to SIDEWALK or ROAD.
   * These are candidate spots for storefront buildings to be carved into.
   * Returns one candidate per cluster (thinned to avoid overlaps).
   */
  private findBlockEdgeSpots(
    rx: number,
    ry: number,
    rw: number,
    rh: number,
  ): { x: number; y: number }[] {
    const results: { x: number; y: number }[] = [];
    for (let y = ry + 1; y < ry + rh - 1; y++) {
      for (let x = rx + 1; x < rx + rw - 1; x++) {
        if (x >= MAP_WIDTH || y >= MAP_HEIGHT) continue;
        if (this.grid[y][x] !== TerrainType.WALL) continue;

        // Must be adjacent to a ROAD or SIDEWALK tile (i.e., on the block edge)
        const adjStreet =
          this.isStreetTile(x - 1, y) ||
          this.isStreetTile(x + 1, y) ||
          this.isStreetTile(x, y - 1) ||
          this.isStreetTile(x, y + 1);
        if (!adjStreet) continue;

        results.push({ x, y });
      }
    }
    // Thin out: keep at most one per 3x3 area to spread buildings out
    return this.thinPoints(results, 3);
  }

  /** Check if a tile is a street-accessible tile (ROAD or SIDEWALK). */
  private isStreetTile(x: number, y: number): boolean {
    if (x < 0 || x >= MAP_WIDTH || y < 0 || y >= MAP_HEIGHT) return false;
    const t = this.grid[y][x];
    return t === TerrainType.ROAD || t === TerrainType.SIDEWALK;
  }

  /**
   * Search outward from (cx, cy) up to `radius` tiles for a spot where
   * a building footprint of size (w x h) can be carved into a block edge.
   * The footprint must be entirely WALL tiles, and at least one side
   * must be adjacent to a ROAD or SIDEWALK tile.
   */
  private findBlockEdgeClearSpot(
    cx: number,
    cy: number,
    w: number,
    h: number,
    radius: number,
  ): { x: number; y: number } | null {
    for (let r = 0; r <= radius; r++) {
      for (let dy = -r; dy <= r; dy++) {
        for (let dx = -r; dx <= r; dx++) {
          if (Math.abs(dx) !== r && Math.abs(dy) !== r && r > 0) continue;
          const tx = cx + dx;
          const ty = cy + dy;
          if (this.canPlaceBuilding(tx, ty, w, h)) {
            return { x: tx, y: ty };
          }
        }
      }
    }
    return null;
  }

  // ─── Intersection / placement helpers ───────────────────────────────────

  /**
   * Find major intersections: where two 2-tile major roads cross.
   * Major roads are at positions divisible by 16.
   */
  private findMajorIntersections(
    rx: number,
    ry: number,
    rw: number,
    rh: number,
  ): { x: number; y: number }[] {
    const results: { x: number; y: number }[] = [];
    for (let my = ry; my < ry + rh; my += 16) {
      for (let mx = rx; mx < rx + rw; mx += 16) {
        if (mx < MAP_WIDTH && my < MAP_HEIGHT) {
          results.push({ x: mx, y: my });
        }
      }
    }
    return results;
  }

  /**
   * Remove points closer than `minDist` tiles to each other (greedy).
   */
  private thinPoints(
    points: { x: number; y: number }[],
    minDist: number,
  ): { x: number; y: number }[] {
    const kept: { x: number; y: number }[] = [];
    for (const p of points) {
      const tooClose = kept.some(
        (k) =>
          Math.abs(k.x - p.x) < minDist && Math.abs(k.y - p.y) < minDist,
      );
      if (!tooClose) kept.push(p);
    }
    return kept;
  }

  /**
   * Check whether a building footprint can be placed at (tx, ty).
   * All tiles in the footprint must be WALL (carving into a solid block).
   * At least one edge of the footprint must be adjacent to a ROAD or
   * SIDEWALK tile so the storefront faces a street.
   */
  private canPlaceBuilding(
    tx: number,
    ty: number,
    w: number,
    h: number,
  ): boolean {
    if (tx < 0 || ty < 0 || tx + w > MAP_WIDTH || ty + h > MAP_HEIGHT) {
      return false;
    }

    // All footprint tiles must be WALL (solid block interior)
    for (let yy = ty; yy < ty + h; yy++) {
      for (let xx = tx; xx < tx + w; xx++) {
        const t = this.grid[yy][xx];
        if (t !== TerrainType.WALL) return false;
      }
    }

    // At least one edge tile must be adjacent to ROAD or SIDEWALK
    // Check all four sides of the footprint rectangle
    let hasStreetAccess = false;

    // Top edge (y = ty - 1)
    if (ty > 0) {
      for (let xx = tx; xx < tx + w && !hasStreetAccess; xx++) {
        if (this.isStreetTile(xx, ty - 1)) hasStreetAccess = true;
      }
    }
    // Bottom edge (y = ty + h)
    if (!hasStreetAccess && ty + h < MAP_HEIGHT) {
      for (let xx = tx; xx < tx + w && !hasStreetAccess; xx++) {
        if (this.isStreetTile(xx, ty + h)) hasStreetAccess = true;
      }
    }
    // Left edge (x = tx - 1)
    if (!hasStreetAccess && tx > 0) {
      for (let yy = ty; yy < ty + h && !hasStreetAccess; yy++) {
        if (this.isStreetTile(tx - 1, yy)) hasStreetAccess = true;
      }
    }
    // Right edge (x = tx + w)
    if (!hasStreetAccess && tx + w < MAP_WIDTH) {
      for (let yy = ty; yy < ty + h && !hasStreetAccess; yy++) {
        if (this.isStreetTile(tx + w, yy)) hasStreetAccess = true;
      }
    }

    return hasStreetAccess;
  }

  /**
   * Carve a building footprint out of a solid block. Converts all
   * footprint tiles from WALL to BUILDING_FLOOR, making that section
   * walkable and enterable from the adjacent street.
   *
   * Also ensures a 1-tile SIDEWALK entry point exists between the
   * storefront and the nearest road if one doesn't already exist.
   */
  private stampBuildingFootprint(
    tx: number,
    ty: number,
    w: number,
    h: number,
  ): void {
    // Carve the interior — all tiles become BUILDING_FLOOR
    for (let yy = ty; yy < ty + h; yy++) {
      for (let xx = tx; xx < tx + w; xx++) {
        this.grid[yy][xx] = TerrainType.BUILDING_FLOOR;
      }
    }

    // Ensure at least one entry point: find the side adjacent to a street
    // and make sure there is a walkable connection. If the adjacent tile
    // is WALL, convert it to SIDEWALK to create an entry.
    this.ensureStorefrontEntry(tx, ty, w, h);
  }

  /**
   * Ensure there is at least one walkable tile connecting the building
   * footprint to the street network. Checks all four sides and converts
   * an adjacent WALL tile to SIDEWALK if needed.
   */
  private ensureStorefrontEntry(
    tx: number,
    ty: number,
    w: number,
    h: number,
  ): void {
    // Check if any footprint edge tile already has a direct walkable
    // neighbor (ROAD, SIDEWALK, ALLEY, or PARK)
    const hasDirectAccess = this.footprintHasStreetAccess(tx, ty, w, h);
    if (hasDirectAccess) return;

    // No direct access — find the nearest WALL tile adjacent to both
    // the footprint AND a street tile, and convert it to SIDEWALK
    // Check top edge
    if (ty > 0) {
      for (let xx = tx; xx < tx + w; xx++) {
        if (this.grid[ty - 1][xx] === TerrainType.WALL) {
          // Check if this WALL tile is itself adjacent to a street
          if (
            this.isStreetTile(xx, ty - 2) ||
            this.isStreetTile(xx - 1, ty - 1) ||
            this.isStreetTile(xx + 1, ty - 1)
          ) {
            this.grid[ty - 1][xx] = TerrainType.SIDEWALK;
            return;
          }
        }
      }
    }
    // Check bottom edge
    if (ty + h < MAP_HEIGHT) {
      for (let xx = tx; xx < tx + w; xx++) {
        if (this.grid[ty + h][xx] === TerrainType.WALL) {
          if (
            this.isStreetTile(xx, ty + h + 1) ||
            this.isStreetTile(xx - 1, ty + h) ||
            this.isStreetTile(xx + 1, ty + h)
          ) {
            this.grid[ty + h][xx] = TerrainType.SIDEWALK;
            return;
          }
        }
      }
    }
    // Check left edge
    if (tx > 0) {
      for (let yy = ty; yy < ty + h; yy++) {
        if (this.grid[yy][tx - 1] === TerrainType.WALL) {
          if (
            this.isStreetTile(tx - 2, yy) ||
            this.isStreetTile(tx - 1, yy - 1) ||
            this.isStreetTile(tx - 1, yy + 1)
          ) {
            this.grid[yy][tx - 1] = TerrainType.SIDEWALK;
            return;
          }
        }
      }
    }
    // Check right edge
    if (tx + w < MAP_WIDTH) {
      for (let yy = ty; yy < ty + h; yy++) {
        if (this.grid[yy][tx + w] === TerrainType.WALL) {
          if (
            this.isStreetTile(tx + w + 1, yy) ||
            this.isStreetTile(tx + w, yy - 1) ||
            this.isStreetTile(tx + w, yy + 1)
          ) {
            this.grid[yy][tx + w] = TerrainType.SIDEWALK;
            return;
          }
        }
      }
    }
  }

  /**
   * Check if any tile immediately adjacent to the footprint (outside it)
   * is a walkable street tile (ROAD, SIDEWALK, ALLEY, BUILDING_FLOOR).
   */
  private footprintHasStreetAccess(
    tx: number,
    ty: number,
    w: number,
    h: number,
  ): boolean {
    // Top edge
    if (ty > 0) {
      for (let xx = tx; xx < tx + w; xx++) {
        if (this.isWalkableTile(xx, ty - 1)) return true;
      }
    }
    // Bottom edge
    if (ty + h < MAP_HEIGHT) {
      for (let xx = tx; xx < tx + w; xx++) {
        if (this.isWalkableTile(xx, ty + h)) return true;
      }
    }
    // Left edge
    if (tx > 0) {
      for (let yy = ty; yy < ty + h; yy++) {
        if (this.isWalkableTile(tx - 1, yy)) return true;
      }
    }
    // Right edge
    if (tx + w < MAP_WIDTH) {
      for (let yy = ty; yy < ty + h; yy++) {
        if (this.isWalkableTile(tx + w, yy)) return true;
      }
    }
    return false;
  }

  /** Check if a tile is walkable (any terrain with finite infantry cost). */
  private isWalkableTile(x: number, y: number): boolean {
    if (x < 0 || x >= MAP_WIDTH || y < 0 || y >= MAP_HEIGHT) return false;
    return isFinite(TERRAIN_COSTS[this.grid[y][x]]);
  }
}
